export function buildLogEntry({
  activityType,
  description,
  oldValue = null,
  newValue = null,
  changeNote = '',
  walletEffect = null,
  status = 'success',
  errorMessage = null,
}) {
  return {
    activityType,
    description,
    oldValue,
    newValue,
    changeNote,
    walletEffect,
    status,
    errorMessage,
  }
}

export const ACTIVITY_LABELS = {
  ATTACH_PAYMENT_SLIP: 'แนบสลิปการจ่าย',
  PAYMENT_EDIT: 'แก้ไขรายการจ่าย',
  PAYMENT_UNDO: 'ยกเลิกการจ่าย',
  ADD_INCOME: 'เพิ่มรายรับ',
  ADD_EXPENSE: 'เพิ่มรายจ่าย',
  EDIT_INCOME: 'แก้ไขรายรับ',
  EDIT_EXPENSE: 'แก้ไขรายจ่าย',
  DELETE_TRANSACTION: 'ลบรายการ',
  CANCEL_TRANSACTION: 'ยกเลิกรายการ',
  PAY_PENDING: 'ชำระค้างชำระ',
  CASH_DEPOSIT: 'ฝากเงินสด',
  BANK_DEPOSIT: 'รับเงินเข้าบัญชี',
  BANK_WITHDRAW: 'จ่ายเงินออกจากบัญชี',
  TRANSFER_TO_WALLET: 'ย้ายเงินสด → เงินโอน',
  WITHDRAW_FROM_TRANSFER: 'ถอนเงินโอน → เงินสด',
  TRANSFER_ACCOUNT_CREATE: 'สร้างบัญชีเงินโอน',
  TRANSFER_ACCOUNT_UPDATE: 'แก้ไขบัญชีเงินโอน',
  TRANSFER_ACCOUNT_DELETE: 'ลบบัญชีเงินโอน',
  TRANSFER_ACCOUNT_MOVE: 'ย้ายเงินระหว่างบัญชี',
  CARD_CREATE: 'เพิ่มบัตรเครดิต',
  CARD_UPDATE: 'แก้ไขบัตรเครดิต',
  CARD_DELETE: 'ลบบัตรเครดิต',
  CARD_ADJUST: 'ปรับยอดหนี้บัตร',
  CARD_PAYMENT: 'จ่ายบิลบัตรเครดิต',
  CARD_PAYMENT_UNDO: 'ย้อนการจ่ายบิลบัตร',
  CARD_PREPAY: 'จ่ายรายการบัตรก่อนออกบิล',
  CARD_PREPAY_UNDO: 'ย้อนการจ่ายรายการบัตรก่อนออกบิล',
  INSTALLMENT_CREATE: 'เริ่มผ่อนชำระ',
  INSTALLMENT_PAY: 'จ่ายค่างวดผ่อน',
  INSTALLMENT_PAY_UNDO: 'ย้อนการจ่ายค่างวด',
  INSTALLMENT_SETTLE: 'ปิดยอดผ่อนก่อนกำหนด',
  INSTALLMENT_CANCEL: 'ยกเลิกการผ่อน',
  INSTALLMENT_EDIT: 'แก้ไขรายการผ่อน',
  INSTALLMENT_DELETE: 'ลบรายการผ่อน',
  CARD_CASHBACK: 'เงินคืนเข้าบัตร',
  CARD_AUTOPAY: 'ยืนยันหักบัญชีอัตโนมัติ',
  CARD_ADVANCE: 'กดเงินสดจากบัตร',
  CARD_ADVANCE_UNDO: 'ย้อนการกดเงินสด',
  CARD_FEE: 'ค่าธรรมเนียมรายปีบัตร',
  DEBT_CREATE: 'เพิ่มหนี้สิน',
  DEBT_PAY: 'จ่ายค่างวดหนี้',
  DEBT_RECEIVE: 'รับคืนงวดหนี้',
  DEBT_UNDO: 'ย้อนการจ่ายงวดหนี้',
  DEBT_SETTLE: 'ปิดยอดหนี้ก่อนกำหนด',
  DEBT_CANCEL: 'ยกเลิกหนี้สิน',
  DEBT_UPDATE: 'แก้ไขข้อมูลหนี้สิน',
  SUB_CREATE: 'สร้างกระเป๋าตังค์',
  SUB_DELETE: 'ลบกระเป๋าตังค์',
  SUB_RENAME: 'เปลี่ยนชื่อกระเป๋า',
  SUB_DEPOSIT: 'ฝากเงินเข้ากระเป๋า',
  SUB_WITHDRAW: 'ถอนเงินจากกระเป๋า',
  SUB_TRANSFER: 'โอนระหว่างกระเป๋า',
  SUB_BORROW: 'ยืมเงินจากกระเป๋า',
  SUB_RETURN: 'คืนเงินกระเป๋า',
  RECEIVE_TAX_INVOICE: 'รับใบกำกับภาษี',
  IMPORT_DATA: 'นำเข้าข้อมูล',
  BACKUP_DATA: 'สำรองข้อมูล',
  RESET_LEDGER: 'ล้างรายการเดินบัญชี',
  RESET_ALL: 'ล้างข้อมูลทั้งหมด',
  RESTORE_BACKUP: 'กู้คืนข้อมูล',
  ADD_INCOME_MAIN: 'รับเงิน',
  OPEN_BILL: 'เปิดบิลค้างชำระ',
  ADD_OTHER_INCOME: 'รับเงินประเภทอื่นๆ',
  OPEN_BILL_INCOME: 'เปิดบิลรอรับเงิน',
  RECEIVE_INCOME: 'รับเงินจากรายการรอ',
  CREATE_TAX_INVOICE: 'สร้างรอใบกำกับภาษี',
  DELETE_TAX_INVOICE: 'ยกเลิกรอใบกำกับภาษี',
  CREATE_PENDING: 'สร้างรายการค้างชำระ',
  DELETE_PENDING: 'ยกเลิกรายการค้างชำระ',
  SETTINGS_BACKUP: 'สำรองการตั้งค่า',
  SETTINGS_RESTORE: 'กู้คืนการตั้งค่า',
  LOG_EXPORT: 'ดาวน์โหลดประวัติ',
  LOG_CLEAR_OLD: 'ล้างประวัติเก่า',
  REPORT_EXPORT: 'ส่งออกรายงาน',
  CATEGORY_CREATE: 'สร้างหมวดหมู่',
  CATEGORY_UPDATE: 'แก้ไขหมวดหมู่',
  CATEGORY_DELETE: 'ลบหมวดหมู่',
  VENDOR_CREATE: 'สร้างผู้ขาย',
  VENDOR_UPDATE: 'แก้ไขผู้ขาย',
  VENDOR_DELETE: 'ลบผู้ขาย',
  QUICK_ITEM_CREATE: 'สร้างรายการด่วน',
  QUICK_ITEM_UPDATE: 'แก้ไขรายการด่วน',
  QUICK_ITEM_DELETE: 'ลบรายการด่วน',
  CALENDAR_NOTE_CREATE: 'สร้างโน้ตปฏิทิน',
  CALENDAR_NOTE_UPDATE: 'แก้ไขโน้ตปฏิทิน',
  CALENDAR_NOTE_DELETE: 'ลบโน้ตปฏิทิน',
  UPLOAD_RECEIPT: 'อัปโหลดใบเสร็จ',
  UPLOAD_TAX_INVOICE_FILE: 'อัปโหลดไฟล์ใบกำกับภาษี',
  UPLOAD_FILE_FAILED: 'อัปโหลดไฟล์ไม่สำเร็จ',
  RECURRING_CREATE: 'สร้างรายการประจำ',
  RECURRING_UPDATE: 'แก้ไขรายการประจำ',
  RECURRING_DELETE: 'ลบรายการประจำ',
  RECURRING_PAID: 'จ่ายรายการประจำ',
  RECURRING_UNPAID: 'ยกเลิกการจ่ายรายการประจำ',
  RECURRING_SKIPPED: 'ข้ามรายการประจำ',
  RECURRING_GENERATE: 'สร้างรายการประจำรายเดือน',
}
